---
title: "HW4"
output: html_document
date: "2026-03-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)

cars93 <- MASS::Cars93
baseplot <- ggplot(cars93, aes(x = Price, y = Fuel.tank.capacity)) +
  geom_point(color = "grey60") +
  scale_x_continuous(
    name = "price (USD)",
    breaks = c(20, 40, 60),
    labels = c("$20,000", "$40,000", "$60,000")
  ) +
  scale_y_continuous(name = "fuel-tank capacity\n(US gallons)")

```

```{r}
p_lm <- baseplot +
geom_smooth(se = TRUE, method = "lm",  color = "#8fe388") +
  ggtitle("LM method") +
  theme(plot.title = element_text(size=14, color = "#8fe388"))

p_lm
```

```{r}
p_glm <- baseplot +
geom_smooth(se = TRUE, method = "glm", color = "#fe8d6d") +
  ggtitle("GLM method") +
  theme(plot.title = element_text(size=14, color = "#fe8d6d"))

p_glm
```

```{r}
p_gam <- baseplot +
geom_smooth(se = TRUE, method = "gam",  color = "#7c6bea") +
  ggtitle("GAM method") +
  theme(plot.title = element_text(size=14, color = "#7c6bea"))

p_gam
```

```{r}
library(tidyverse)
library(ggplot2)
install.packages('ggridges')
library(ggridges)
library(lubridate)
library(ggrepel)
library(colorspace)
```

```{r}
folder_location='...'

setwd(folder_location)
load("./preprint_growth.rda")

head(preprint_growth)

preprint_growth %>% filter(archive == "bioRxiv") %>%
  filter(count > 0) -> biorxiv_growth

preprint_growth %>% filter(archive %in% c("bioRxiv", "arXiv q-bio", "PeerJ Preprints")) %>%
  filter(count > 0) %>%
  mutate(archive = factor(archive, levels = c("bioRxiv", "arXiv q-bio", "PeerJ Preprints")))-> preprints

```

```{r}
preprint_full <- preprint_growth %>% drop_na() %>% filter(count>0, date > as.Date('2004-12-30'))

preprint_final2 <- preprint_full %>% filter(archive %in% c("bioRxiv", "F1000Research"))

```

```{r}
preprints_final <- filter(preprint_final2, date == ymd("2017-01-01"))
ggplot(preprint_final2) +
  aes(date, count, color = archive, fill = archive, shape = archive) + 
  geom_line(size = 1) + 
  labs(title="Preprint Counts") +
  #geom_point(color = "white", size = 2) +
  scale_y_continuous(
    limits = c(0, 600), expand = c(0, 0),
    name = "preprints / month",
    sec.axis = dup_axis(
      breaks = preprints_final$count,
      labels = preprints_final$archive,
      name = NULL)
  ) +
  scale_x_date(limits=c(as.Date("2014-1-1"), ymd("2017-02-01")))+
  scale_color_manual(values = c("#0072b2", "#D55E00", "#009e73"),
                     name = NULL) +
  scale_fill_manual(values = c("#0072b2", "#D55E00", "#009e73"),
                    name = NULL) +
  scale_shape_manual(values = c(21, 22, 23),
                     name = NULL) + 
  coord_cartesian(clip = "off") +
  #theme_dviz_open() +
  theme(legend.position = "right") +
  theme(axis.line.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.text.y.right = element_text(margin = margin(0, 0, 0, 0)),
        plot.margin = margin(14, 7, 3, 1.5))

```

```{r}
preprints_final <- filter(preprints, date == ymd("2017-01-01"))
ggplot(preprints) +
  aes(date, count, color = archive, fill = archive, shape = archive) + 
  geom_line(size = 1) + 
  #geom_point(color = "white", size = 2) +
  scale_y_continuous(
    limits = c(0, 600), expand = c(0, 0),
    name = "preprints / month",
    sec.axis = dup_axis(
      breaks = preprints_final$count,
      labels = c("arXiv\nq-bio", "PeerJ\nPreprints", "bioRxiv"),
      name = NULL)
  ) + 
  scale_x_date(name = "year",
               limits = c(min(biorxiv_growth$date), ymd("2017-01-01")),
               expand = expand_scale(mult = c(0.02, 0))) +
  scale_color_manual(values = c("#0072b2", "#D55E00", "#009e73"),
                     name = NULL) +
  scale_fill_manual(values = c("#0072b2", "#D55E00", "#009e73"),
                    name = NULL) +
  scale_shape_manual(values = c(21, 22, 23),
                     name = NULL) + 
  coord_cartesian(clip = "off") +
  #theme_dviz_open() +
  theme(legend.position = "none") +
  theme(axis.line.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.text.y.right = element_text(margin = margin(0, 0, 0, 0)),
        plot.margin = margin(14, 7, 3, 1.5))
```